--- #My first YAML Playbook for Ansible
- hosts: apacheweb
  user: vagrant
  become: yes
  connection: ssh
  gather_facts: no
  vars:
    playbook_version: 0.1b
  vars_files:
    - conf/copyright.yml
    - conf/webdefaults.yml
  vars_prompt:
    - name: Web_domain
      prompt: Web Domain
  tasks:
    - name: Install Lynx Web Browser
      action: yum name=lynx state=installed
    - name: Check for Telnet client
      action: yum name=telnet state=absent